trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

variables:
  hugo.version: '0.60.1'
  blog.path: '.'

steps:

- checkout: self
  displayName: 'Checkout repository including submodules'
  submodules: true  # true so Hugo theme submodule is checked out

- script: |
   wget -c https://github.com/gohugoio/hugo/releases/download/v$(hugo.version)/hugo_$(hugo.version)_Linux-64bit.deb   
  displayName: "Download HUGO"

- script: 'sudo dpkg -i hugo_$(hugo.version)_Linux-64bit.deb'
  displayName: "Install HUGO"

- script: |
   cd $(blog.path)
   hugo --log --verboseLog --config config.toml
  displayName: 'Generate Website'

- task: CopyFiles@2
  displayName: 'Copy Website'
  inputs:
    SourceFolder: '$(blog.path)/public'
    Contents: "**"
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Drop Website'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: Drop
    publishLocation: 'Container'