# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

variables:
  hugo.version: '0.55.6'
  blog.path: '.'

steps:
- script: echo Hello, Hugobuilder!
  displayName: 'Here we Go'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
   wget -c https://github.com/gohugoio/hugo/releases/download/v$(hugo.version)/hugo_$(hugo.version)_Linux-64bit.deb   
  displayName: "Download HUGO"

- script: 'sudo dpkg -i hugo_$(hugo.version)_Linux-64bit.deb'
  displayName: "Install HUGO"

- script: |
   cd $(blog.path)
   hugo --log -v
  displayName: 'Generate Blog'

- task: CopyFiles@2
  displayName: 'Copy Blog'
  inputs:
    SourceFolder: '$(blog.path)/public'
    Contents: "**"
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: Publish Blog
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: Drop
    publishLocation: 'Container'