baseURL = "https://filmclub.brussels/"
languageCode = "en-us"
title = "filmclub"
theme = "mediumish"
summaryLength = 25
copyright = "filmclub 2019"
disqusShortname = "filmclub-1"
googleAnalytics = "UA-137589012-1"

[taxonomies]
leden = "leden"

[params]
logo = "/images/logo.png"
#  description ="De filmclub is een film club!"
mailchimp = "https://dupon.us19.list-manage.com/subscribe/post?u=328bef6db0889927f790ae755&amp;id=57e185d01c"
mailprotect = "b_328bef6db0889927f790ae755_57e185d01c"
#[params.author]
#  name = "Bart"
#  thumbnail = "/images/author.png"
#  description = "Voorzitter"

[params.index]
#  picture = "/images/author.png"
  title = "Welkom bij filmclub"
  subtitle = ""
  mdtext = '''\
1. Bekijk de <A href="/gepland">geplande films</a>\
2. Kom naar de film\
3. Herhaal drie keer en ontvang je lidkaart!\
\
Leden:\
#001 bdu (04/04/2019)\
#002 has (29/04/2019)\
#003 nam (07/05/2019)\
#004 mva (28/05/2019)\
'''
  alertbar = true
  
## Main Menu
[[menu.main]]
    name = "Gepland"
    weight = 100
    identifier = "gepland"
    url = "/gepland"
[[menu.main]]
    name = "Archief"
    weight = 150
    identifier = "archief"
    url = "/archief"
[[menu.main]]
    name = "Blog"
    weight = 200
    identifier = "blog"
    url = "/blog"
    
