baseURL = "https://filmclub.github.io/"
languageCode = "en-us"
title = "filmclub"
theme = "mediumish"
summaryLength = 25
copyright = "filmclub 2019"
disqusShortname = "filmclub-1"
googleAnalytics = "UA-137589012-1"

[params]
logo = "/images/logo.png"
#  description ="the clean blog!"
#  mailchimp = "you can provide a mailchimp-link here"

#[params.author]
#  name = "Bart"
#  thumbnail = "/images/author.png"
#  description = "Voorzitter"

[params.index]
#  picture = "/images/author.png"
  title = "Welkom bij filmclub"
  subtitle = ""
  mdtext = '''\
1. Klik op "films" voor planning\
2. Kom naar de film\
3. Herhaal drie keer en ontvang je lidkaart!\
'''
  alertbar = false
  ## Main Menu
[[menu.main]]
    name = "Films"
    weight = 100
    identifier = "films"
    url = "/films"