baseURL = "https://filmclub.brussels/"
languageCode = "en-us"
title = "filmclub"
theme = "mediumish"
summaryLength = 25
copyright = "filmclub 2019 - 2024"
# disqusShortname = ""
# googleAnalytics = ""

[taxonomies]
leden = "leden"

[params]
logo = "/images/logo.png"

#[params.author]
#  name = "Bart"
#  thumbnail = "/images/author.png"
#  description = "Voorzitter"
  
## Main Menu
[[menu.main]]
    name = "Gepland"
    weight = 100
    identifier = "gepland"
    url = "/gepland"
[[menu.main]]
    name = "Archief"
    weight = 150
    identifier = "archief"
    url = "/archief"    
