baseURL = "https://filmclub.brussels/"
languageCode = "en-us"
title = "filmclub"
theme = "mediumish"
summaryLength = 25
copyright = "filmclub 2019"
# disqusShortname = ""
# googleAnalytics = ""

[taxonomies]
leden = "leden"

[params]
logo = "/images/logo.png"
mailchimp = "https://dupon.us19.list-manage.com/subscribe/post?u=328bef6db0889927f790ae755&amp;id=57e185d01c"
mailprotect = "b_328bef6db0889927f790ae755_57e185d01c"

#[params.author]
#  name = "Bart"
#  thumbnail = "/images/author.png"
#  description = "Voorzitter"

  
## Main Menu
[[menu.main]]
    name = "Gepland"
    weight = 100
    identifier = "gepland"
    url = "/gepland"
[[menu.main]]
    name = "Archief"
    weight = 150
    identifier = "archief"
    url = "/archief"
[[menu.main]]
    name = "Blog"
    weight = 200
    identifier = "blog"
    url = "/blog"
    
